Dap.Mtp: convert static field 'empty_file' to non-static
This field being static meant that its initialization was needed when
inspecting the class via Reflection, which caused a crash when using
the GSettingsSchemaExtractor:

Found SchemaEntry: Banshee.Dap.Mtp.MtpSource.NeverSyncAlbumArtSchema

Unhandled Exception:
System.TypeInitializationException: An exception was thrown by the type initializer for Banshee.Dap.Mtp.MtpSource ---> System.ArgumentException: First component must not be null or empty
Parameter name: first
  at Hyena.Paths.Combine (System.String first, System.String[] components) [0x0006c] in /home/andres1210/Code/bansheeGTK3/src/Hyena/Hyena/Hyena/Paths.cs:89
  at Banshee.Dap.Mtp.MtpSource..cctor () [0x00000] in /home/andres1210/Code/bansheeGTK3/src/Dap/Banshee.Dap.Mtp/Banshee.Dap.Mtp/MtpSource.cs:266
  --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.MonoField:GetValueInternal (System.Reflection.MonoField,object)
  at System.Reflection.MonoField.GetValue (System.Object obj) [0x0006a] in /home/andres1210/Code/mono/mcs/class/corlib/System.Reflection/MonoField.cs:125
  at GSettingsSchemaExtractorProgram.Extract (IEnumerable`1 types) [0x000ad] in /home/andres1210/Code/bansheeGTK3/build/GSettingsSchemaExtractor.cs:78
  at GSettingsSchemaExtractorProgram.Extract (System.IO.DirectoryInfo dir) [0x000ae] in /home/andres1210/Code/bansheeGTK3/build/GSettingsSchemaExtractor.cs:48
  at GSettingsSchemaExtractorProgram.Main (System.String[] args) [0x0004f] in /home/andres1210/Code/bansheeGTK3/build/GSettingsSchemaExtractor.cs:27
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for Banshee.Dap.Mtp.MtpSource ---> System.ArgumentException: First component must not be null or empty
Parameter name: first
  at Hyena.Paths.Combine (System.String first, System.String[] components) [0x0006c] in /home/andres1210/Code/bansheeGTK3/src/Hyena/Hyena/Hyena/Paths.cs:89
  at Banshee.Dap.Mtp.MtpSource..cctor () [0x00000] in /home/andres1210/Code/bansheeGTK3/src/Dap/Banshee.Dap.Mtp/Banshee.Dap.Mtp/MtpSource.cs:266
  --- End of inner exception stack trace ---
  at (wrapper managed-to-native) System.Reflection.MonoField:GetValueInternal (System.Reflection.MonoField,object)
  at System.Reflection.MonoField.GetValue (System.Object obj) [0x0006a] in /home/andres1210/Code/mono/mcs/class/corlib/System.Reflection/MonoField.cs:125
  at GSettingsSchemaExtractorProgram.Extract (IEnumerable`1 types) [0x000ad] in /home/andres1210/Code/bansheeGTK3/build/GSettingsSchemaExtractor.cs:78
  at GSettingsSchemaExtractorProgram.Extract (System.IO.DirectoryInfo dir) [0x000ae] in /home/andres1210/Code/bansheeGTK3/build/GSettingsSchemaExtractor.cs:48
  at GSettingsSchemaExtractorProgram.Main (System.String[] args) [0x0004f] in /home/andres1210/Code/bansheeGTK3/build/GSettingsSchemaExtractor.cs:27